name: Build for Netlify



on:
  push:
    branches:
      - main

jobs:
  pdfbuild:
    runs-on: ubuntu-latest
    container: matthewfallon/eisvogel
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: ls
    - run: pwd
    - name: Build PDF
      run: 	pandoc --data-dir=/var/lib/pandoc --template=eisvogel.latex --pdf-engine=xelatex --from markdown+yaml_metadata_block+smart+backtick_code_blocks+grid_tables --to pdf -o "nhstream.pdf" ./index.md ./jobs.md ./power-on.md ./computer.md 
    - run: ls
    - run: pwd
    # - name: Upload Artifact
      

  # jekyllbuild:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.3' # Not needed with a .ruby-version file
  #       bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  #   - name: Build PDF
  #     run: pandoc ./index.md ./jobs.md ./power-on.md ./computer.md --from markdown -o nhstream.pdf --template ./eisvogel.latex
  #   - name: Build Jekyll Site
  #     run: bundle exec jekyll build
  #   - name: Deploy to Netlify
  #     uses: jsmrcaga/action-netlify-deploy@v2.0.0
  #     with:
  #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
  #       NETLIFY_DEPLOY_TO_PROD: true
  #       build_directory: _site
  #       install_command: "echo Skipping installing the dependencies"
  #       build_command: "echo Skipping building the web files"



  